### ISSUE TITLE
Necrobrowser is running and capturing the session details but not opening chromium browser

### ISSUE THREAD

**Issue by rhashi** [muraenateam/necrobrowser#1]
I am using kali linux and I made the changes in config.toml file by changing platform type="linux".

whenever I run the necrobrowser i get this error.

└─$ node necrobrowser.js 
error: check that extrusionPath and profilesPath are existing directories

**Comment by rhashi** [comment]
No issue I solved it. Necrobrowser is running. but its not it is not opening session on chromium

**Comment by ohpe** [comment]
By default Necrobrowser runs in headless mode:`headless = true`.
Change it in the [config](https://github.com/muraenateam/necrobrowser/blob/bb15c59b01120ed6583eda7f164cc336994f7e1b/config.toml#L56) if you want to see the Chromium GUI.

**Comment by kwekudumebi** [comment]
└─$ node necrobrowser.js
error: check that extrusionPath and profilesPath are existing directories
please how could this be solved
