### ISSUE TITLE
task type/name not supported in RESTful API

### ISSUE THREAD

**Issue by ajaja7609** [muraenateam/necrobrowser#2]
Hi! First, thank you for your work!

I'm trying to uses Necrobrowser on Google Account but I'm facing errors when I send the POST /instrument to the API
I'm sending the following body  (with working cookies):

**JSON Body**
``` {
"name": "NecroTest",
"task": {
	"type": "gsuite",
	"name": "ScreenshotApps",
	"params": {
		"fixSession": "https://mail.google.com/mail/u/0/#inbox"
		}
	},
"cookies": [
	
{
	"a": "b",
        "c": "d",
}
]
}
```

**Error in the response**
```
[task:gsuite:J3lWdmurq] initiating necro -> name: [NecroTest] type: [gsuite.S] cookies: [37]
error: task type/name not supported. see GET /tasks output
```

Also I'm not sure how I am supposed to write the credentials in the JSON.

Thanks in advance!

**Comment by antisnatchor** [comment]
Hey, task name is an Array, like:
"name": ["PlantAndDump"],

this is to support parallel tasks.

so in your case you need this:
"type": "gsuite",
"name": ["ScreenshotApps"],
